name: Build and Execute C++ Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cpp-project-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Download enwik9.zip
        run: |
          wget http://mattmahoney.net/dc/enwik9.zip
          unzip enwik9.zip

      - name: Make Scripts Executable
        run: |
          chmod +x install_tools/install_upx.sh
          chmod +x install_tools/install_clang-17.sh
          chmod +x build_and_construct_comp.sh

      - name: Install clang-17
        run: ./install_tools/install_clang-17.sh

      - name: Install UPX
        run: ./install_tools/install_upx.sh

      - name: Build Project
        run: ./build_and_construct_comp.sh

      - name: Execute Runner File
        run: |
          cd ./run
          cp ../enwik9 ./
          ./cmix -e enwik9 enwik9.comp
